/*
 * @Descripttion: 
 * @version: 
 * @Author: zyc
 * @Date: 2020-05-21 17:06:07
 * @LastEditors: ywl
 * @LastEditTime: 2020-10-22 17:42:38
 */
/* Automatically generated by './build/bin/build-entry.js' */

import { IhButton } from '../packages/buttom/index';
import { IhButtom2 } from '../packages/buttom2/index';
import { IhTree } from '../packages/tree/index';
import { IhTableRadio } from '../packages/table-radio/index';
import { IhTableCustomColumn } from '../packages/table-custom-column/index';
import { IhSelectTree } from '../packages/select-tree/index';
import { IhCard } from '../packages/card/index';
import { IhDialog } from '../packages/dialog/index';
import { IhPage } from '../packages/page/index';
import { IhFilePre } from '../packages/file-pre/index';
import { IhUpload } from '../packages/upload/index';
import { IhTable } from '../packages/table';
import { IhCascader } from '../packages/cascader';
import { IhSelectPageUser, IhSelectPageBase } from '../packages/select-page';
const components = [
  IhButton,
  IhButtom2,
  IhTree,
  IhTableRadio,
  IhTableCustomColumn,
  IhSelectTree,
  IhCard,
  IhDialog,
  IhPage,
  IhFilePre,
  IhUpload,
  IhTable,
  IhCascader,
  IhSelectPageUser,
  IhSelectPageBase
];
const install = function (vue: Vue | any) {
  components.forEach(component => {
    vue.component(component.name, component);
  });
};

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

export default {
  // 导出的是对象且必须具有 install，才能被 Vue.use() 方法安装
  install
};
