/*
 * @Description: 
 * @version: 
 * @Author: zyc
 * @Date: 2020-05-21 17:06:07
 * @LastEditors: zyc
 * @LastEditTime: 2021-02-17 16:04:53
 */
/* Automatically generated by './build/bin/build-entry.js' */


import { IhTree } from '../packages/tree/index';
import { IhTableRadio } from '../packages/table-radio/index';
import { IhTableCustomColumn } from '../packages/table-custom-column/index';
import { IhSelectTree, IhSelectOrgTreeByUser } from '../packages/select-tree/index';
import { IhSelectOrgTree } from '../packages/select-tree/index';
import { IhDialog } from '../packages/dialog/index';
import { IhPage } from '../packages/page/index';
import { IhFilePre } from '../packages/file-pre/index';
import { IhUpload, IhImgViews } from '../packages/upload/index';
import { IhTable } from '../packages/table';
import { IhCascader } from '../packages/cascader';
import { IhFilePreview } from '../packages/file-preview';
import {
  IhSelectPageByDeveloper,
  IhSelectPageByCompany,
  IhSelectPageDivision,
  IhSelectPageByChannel,
  IhSelectPageByProject,
  IhSelectPageByCycle,
  IhSelectPageByBuild,
  IhSelectPageByRoom,
  IhSelectPageUser,
  IhSelectPageOrg,
  IhSelectPageBase,
  IhSelectPageByPayer,
  IhSelectPageByOrgCompany
} from '../packages/select-page';
// import { IhSelectPageDivision } from '../packages/select-page';
import { IhTableCheckBox } from '../packages/table-checkbox'
import { IhLeftRightContainer } from '../packages/left-right-container'

export default (Vue: any) => {
  Vue.component("IhTree", IhTree);
  Vue.component("IhTableRadio", IhTableRadio);
  Vue.component("IhTableCustomColumn", IhTableCustomColumn);
  Vue.component("IhTableCustomColumn", IhTableCustomColumn);
  Vue.component("IhSelectTree", IhSelectTree);
  Vue.component("IhDialog", IhDialog);
  Vue.component("IhPage", IhPage);
  Vue.component("IhFilePre", IhFilePre);
  Vue.component("IhUpload", IhUpload);
  Vue.component("IhImgViews", IhImgViews);
  Vue.component("IhTable", IhTable);
  Vue.component("IhCascader", IhCascader);
  Vue.component("IhSelectPageDivision", IhSelectPageDivision);
  Vue.component("IhSelectPageByChannel", IhSelectPageByChannel);
  Vue.component("IhSelectPageOrg", IhSelectPageOrg);
  Vue.component("IhSelectPageUser", IhSelectPageUser);
  Vue.component("IhSelectPageByDeveloper", IhSelectPageByDeveloper);
  Vue.component("IhSelectPageByCompany", IhSelectPageByCompany);
  Vue.component("IhSelectPageByProject", IhSelectPageByProject);
  Vue.component("IhSelectPageByCycle", IhSelectPageByCycle);
  Vue.component("IhSelectPageByBuild", IhSelectPageByBuild);
  Vue.component("IhSelectPageByRoom", IhSelectPageByRoom);
  Vue.component("IhSelectPageBase", IhSelectPageBase);
  Vue.component("IhTableCheckBox", IhTableCheckBox);
  Vue.component("IhLeftRightContainer", IhLeftRightContainer);
  Vue.component("IhFilePreview", IhFilePreview);
  Vue.component("IhSelectOrgTree", IhSelectOrgTree);
  Vue.component("IhSelectPageByPayer", IhSelectPageByPayer);
  Vue.component("IhSelectPageByOrgCompany", IhSelectPageByOrgCompany);
  Vue.component("IhSelectOrgTreeByUser", IhSelectOrgTreeByUser);

};
